# Generated by Django 5.0.4 on 2024-04-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Merchant_area', models.CharField(max_length=255)),
                ('Product_name', models.CharField(max_length=255)),
                ('Category', models.CharField(choices=[('asam', 'Asam'), ('manis', 'Manis'), ('gurih', 'Gurih')], max_length=13)),
                ('Product_description', models.CharField(max_length=255)),
                ('Image', models.URLField()),
            ],
        ),
    ]
