# Generated by Django 5.0.4 on 2024-04-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='food',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='food',
            name='Merchant_area',
        ),
        migrations.RemoveField(
            model_name='food',
            name='Product_description',
        ),
        migrations.RemoveField(
            model_name='food',
            name='Product_name',
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(blank=True, choices=[('nasi', 'Nasi'), ('snack', 'Snack'), ('mie', 'Mie'), ('lainnya', 'Lainnya')], max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='merchant_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
