# Generated by Django 3.2.7 on 2024-04-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='Product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='Merchant_area',
            new_name='merchant_area',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='Product_name',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='food',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='food',
            name='Image',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('nasi', 'Nasi'), ('snack', 'Snack'), ('mie', 'Mie'), ('lainnya', 'Lainnya')], default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='merchant_name',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
