# Generated by Django 5.0.4 on 2024-04-21 15:55

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "foods")

class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_remove_food_category_remove_food_image_and_more'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]

    

